"""update collection requests schema

Revision ID: 2485c5ffd198
Revises: 
Create Date: 2025-08-17 13:15:58.972589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2485c5ffd198'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('waste_type', sa.String(length=120), nullable=False),
    sa.Column('collection_date', sa.String(length=50), nullable=False),
    sa.Column('collection_time', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_requests')
    # ### end Alembic commands ###
